baseURL = "/"
languageCode = "tr-tr"
title = "Spirit Notes"

# SCSS dosyamızı CSS'e çevirmek için Hugo Pipes'ı etkinleştir
[build]
  [build.processing]
    [build.processing.scss]
      # SCSS'i sıkıştırılmış CSS'e dönüştür
      transpiler = "dartsass"
      target = "css"
      outputStyle = "compressed"

# Markdown ayarları (ToC için)
[markup]
  [markup.tableOfContents]
    startLevel = 2  # h2 başlıklarından itibaren ToC'ye ekle
    endLevel = 4
    ordered = false # Numaralı liste olmasın
  [markup.goldmark.renderer]
    unsafe = true # HTML/JS gömmek için
